apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: dev
spec:
  containers:
    - name: debug-container
      image: appropriate/curl  # This image has curl installed
      command: [ "sleep", "3600" ]  # Keep the container running
